queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
    merge_conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
    update_method: merge
    merge_method: squash
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: automatic approval for skyrpex-bot pull requests
    conditions:
      - author=skyrpex-bot[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving skyrpex-bot
  - name: Automatic merge on approval and successful build
    actions:
      delete_head_branch: {}
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
