import { Component, Project, TextFile } from "projen";

export class Editorconfig extends Component {
  constructor(project: Project) {
    super(project);

    new TextFile(project, ".editorconfig", {
      committed: false,
      marker: true,
      lines: [
        '# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".',
        "root = true",
        "",
        "[*]",
        "indent_style = space",
        "indent_size = 2",
        "end_of_line = lf",
        "charset = utf-8",
        "trim_trailing_whitespace = true",
        "insert_final_newline = true",
        "",
        "[*.md]",
        "trim_trailing_whitespace = false",
        "",
      ],
    });
  }
}
